#!/usr/bin/env bash
# =============================================================================
# AskJohn – setup-john-env.sh
# Core Setup: Environments, John, hashid, and Config-Generation
# =============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/common.sh" || exit 1
CONFIG_FILE="$SCRIPT_DIR/../config.sh"

print_header "GIVE JOHN A HOME (SETUP)"

# 1. OS Detection (Basic)
OS_TYPE="Unknown"
if [[ "$OSTYPE" == "linux-gnu"* ]]; then OS_TYPE="Linux";
elif [[ "$OSTYPE" == "darwin"* ]]; then OS_TYPE="macOS";
elif [[ "$OSTYPE" == "msys" || "$OSTYPE" == "cygwin" ]]; then OS_TYPE="Windows"; fi

# 2. Check for Python & Pip (Required for hashid)
echo -e "${CYAN}Checking Python environment...${NC}"
if ! command -v pip3 &> /dev/null; then
    echo -e "${YELLOW}Pip3 not found. Trying to install...${NC}"
    if [[ "$OS_TYPE" == "macOS" ]]; then brew install python;
    elif [[ "$OS_TYPE" == "Linux" ]]; then sudo apt update && sudo apt install -y python3-pip; fi
fi

# 3. Check/Install hashid
echo -e "${CYAN}Checking for hashid...${NC}"
if ! command -v hashid &> /dev/null; then
    echo -e "${YELLOW}Installing hashid via pip...${NC}"
    pip3 install hashid --break-system-packages 2>/dev/null || pip3 install hashid
else
    echo -e "${GREEN}[OK] hashid is already installed.${NC}"
fi

# 4. Find John the Ripper
echo -e "${CYAN}Searching for John the Ripper binary...${NC}"
JOHN_PATH=$(command -v john)
if [[ -z "$JOHN_PATH" ]]; then
    echo -e "${RED}John not found in PATH.${NC}"
    read -e -p "Please enter the absolute path to your john binary: " JOHN_PATH
fi

# 5. Generate / Update config.sh
echo -e "${CYAN}Generating configuration...${NC}"

# Preserve existing WORDLISTS if config exists
EXISTING_WORDLISTS=""
if [[ -f "$CONFIG_FILE" ]]; then
    EXISTING_WORDLISTS=$(sed -n '/^WORDLISTS=(/,/)/p' "$CONFIG_FILE")
fi

{
    echo "#!/usr/bin/env bash"
    echo "# Automatically generated by setup-john-env.sh"
    echo "OS_FAMILY=\"$OS_TYPE\""
    echo "JOHN_BIN=\"$JOHN_PATH\""
    echo "HASHID_BIN=\"$(command -v hashid)\""
    if [[ -n "$EXISTING_WORDLISTS" ]]; then
        echo "$EXISTING_WORDLISTS"
    else
        echo "WORDLISTS=()"
    fi
} > "$CONFIG_FILE"

chmod +x "$CONFIG_FILE"
echo -e "${GREEN}Setup complete! config.sh updated.${NC}"
sleep 2